### ISSUE TITLE
n step reward

### ISSUE THREAD

**Issue by MingtaoSun** [jakegrigsby/AdvancedPacmanDQNs#2]
According to 
![alt text](https://cdn-images-1.medium.com/max/1600/0*Vn_-ALkkquELhu23.jpg)

At https://github.com/jakegrigsby/keras-rl/blob/n-step-dqn/rl/agents/dqn.py#L343

Should 
    `discounted_reward_batch = self.gamma * q_batch` 
be
    `discounted_reward_batch = (self.gamma ** self.n_step) * q_batch`

Similar to

https://github.com/jakegrigsby/keras-rl/blob/n-step-dqn/rl/agents/dqn.py#L840

**Comment by jakegrigsby** [comment]
Thanks for catching this. Nstep was implemented incorrectly when I first put this up/wrote the article. I ended up fixing it for a [later project](https://github.com/jakegrigsby/lunarDQfD) and then quickly backported it to this one; should've given it a more thorough review.
